extends:
  - ../../_symbol/linters/javascript/default.eslintrc
  - eslint-config-next
  - plugin:import/react
  - plugin:tailwindcss/recommended

rules:
  import/extensions:
    - error
    - always
    - json: always
      js: never
      jsx: never

settings:
  import/resolver:
    jsconfig:
      config: jsconfig.json

env:
  browser: true
  node: true
  es2021: true
